nginx:
  build: ./nginx
  dockerfile: Dockerfile-vm
  ports:
    - "80:80"
  volumes:
    - /f_work_laravel_docker_src:/var/www/html
  links:
    - php-fpm

php-fpm:
  build: ./php-fpm
  volumes:
    - /f_work_laravel_docker_src:/var/www/html  
  links:
    - mysql

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: geonet_db  # ← база создастся автоматически
    MYSQL_USER: geonet_user       # ← пользователь создастся автоматически  
    MYSQL_PASSWORD: geonet_password
  command: ["mysqld", "--innodb-use-native-aio=0"]
  ports:
    - "32001:3306"
  volumes:
    - /f_docker_mysql/data:/var/lib/mysql