version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - php

  php:
    build: ./php-fpm
    volumes:
      - ../src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: geonet_db  # ← база создастся автоматически
      MYSQL_USER: geonet_user       # ← пользователь создастся автоматически  
      MYSQL_PASSWORD: geonet_password
    command: ["mysqld", "--innodb-use-native-aio=0"]
    ports:
      - "32001:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
