version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
    depends_on:
      - php

  php:
    build: ./php-fpm
    volumes:
      - ../src:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=PHP-XDEBUG"
    ports:
      - "9000:9000"   # php-fpm
      - "64055:9003"   # xdebug
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: geonet_db
    ports:
      - "32001:3306"
